version: '3.8'

services:
  nginx:
    image: docker.io/library/nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./ssl/:/etc/nginx/ssl/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
